services:
  vue_app2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./vue_lesson2:/app/vue_lesson2
    ports:
      - "5173:5173"
    working_dir: /app/vue_lesson2
    command: npm run dev

volumes:
  node_modules:
