services:
  vue_app5:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./vue_lesson5:/app/vue_lesson5
    ports:
      - "5173:5173"
    working_dir: /app/vue_lesson5
    command: npm run dev
