services:
  vue_app3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./vue_lesson3:/app/vue_lesson3
    ports:
      - "5173:5173"
    working_dir: /app/vue_lesson3
    command: npm run dev
